# Generated by Django 4.2 on 2023-08-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_ordernum'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='goods',
            field=models.ManyToManyField(blank=True, null=True, to='goods.goods', verbose_name='分类商品'),
        ),
    ]
