# Generated by Django 4.2 on 2023-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='saleInfo',
            field=models.CharField(max_length=256, null=True, verbose_name='分类描述'),
        ),
    ]
