# Generated by Django 4.2 on 2023-09-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='品牌信息'),
        ),
        migrations.AddField(
            model_name='goods',
            name='collectionCount',
            field=models.IntegerField(default=0, verbose_name='收藏人气'),
        ),
        migrations.AddField(
            model_name='goods',
            name='commentCount',
            field=models.IntegerField(default=0, verbose_name='商品评价'),
        ),
        migrations.AddField(
            model_name='goods',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原商品价格'),
        ),
        migrations.AddField(
            model_name='goods',
            name='salesCount',
            field=models.IntegerField(default=0, verbose_name='销量人气'),
        ),
    ]
