# Generated by Django 4.2 on 2023-09-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_brand_goods_collectioncount_goods_commentcount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品规格名称')),
                ('desc', models.CharField(max_length=256, verbose_name='商品规格介绍')),
                ('picture', models.FileField(blank=True, null=True, upload_to='good_color/', verbose_name='商品规格图片')),
                ('disabled', models.BooleanField(default=False, verbose_name='是否可选')),
                ('selected', models.BooleanField(default=False, verbose_name='是否选中')),
            ],
            options={
                'verbose_name_plural': '商品规格',
            },
        ),
    ]
