# Generated by Django 4.2 on 2023-09-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_goodsspecs_spec_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsspecs',
            name='selected',
        ),
    ]
