# Generated by Django 4.2 on 2023-10-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_goodsskus_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsskus',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='组合现价'),
        ),
    ]
