# Generated by Django 4.2.7 on 2023-11-24 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0014_goodsproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_num', models.IntegerField(default=1, verbose_name='商品数量')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goodsskus', verbose_name='商品sku规格')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户购物车',
            },
        ),
    ]
