# Generated by Django 4.2.7 on 2023-11-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='是否选中'),
        ),
    ]
