# Generated by Django 4.2.7 on 2023-11-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_orderpre'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpre',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期'),
        ),
    ]
