# Generated by Django 4.2.7 on 2023-11-25 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0018_orderpre_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=256, verbose_name='收件人姓名')),
                ('concat', models.CharField(max_length=256, verbose_name='联系方式')),
                ('provinceCode', models.CharField(max_length=256, verbose_name='省份编码')),
                ('cityCode', models.CharField(max_length=256, verbose_name='城市编码')),
                ('countyCode', models.CharField(max_length=256, verbose_name='区/县编码')),
                ('address', models.CharField(max_length=256, verbose_name='详细地址')),
                ('isDefault', models.IntegerField(verbose_name='是否为默认地址')),
                ('fullLocation', models.CharField(max_length=256, verbose_name='地址')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收货地址',
            },
        ),
    ]
