# Generated by Django 4.2.7 on 2023-11-27 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0019_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_num', models.IntegerField(verbose_name='购买数量')),
                ('skus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goodsskus', verbose_name='skus')),
            ],
            options={
                'verbose_name_plural': '订单中间模型',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(verbose_name='订单状态')),
                ('countdown', models.IntegerField(verbose_name='倒计时')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('totalMoney', models.IntegerField(verbose_name='商品总价')),
                ('postFee', models.IntegerField(verbose_name='运费')),
                ('payMoney', models.IntegerField(verbose_name='应付金额')),
                ('payChannel', models.CharField(max_length=256, verbose_name='支付方式')),
                ('buyerMessage', models.CharField(max_length=256, verbose_name='买家留言')),
                ('deliverTime', models.CharField(max_length=256, verbose_name='配送时间')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.address', verbose_name='收货地址')),
                ('order_middle', models.ManyToManyField(to='goods.ordermiddle', verbose_name='订单商品参数')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '订单',
            },
        ),
    ]
