# Generated by Django 4.2.7 on 2023-11-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_ordermiddle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_middle',
            field=models.ManyToManyField(null=True, to='goods.ordermiddle', verbose_name='订单商品参数'),
        ),
    ]
