# Generated by Django 4.2.7 on 2023-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_alter_order_order_middle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyerMessage',
            field=models.CharField(max_length=256, null=True, verbose_name='买家留言'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payMoney',
            field=models.IntegerField(null=True, verbose_name='应付金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalMoney',
            field=models.IntegerField(null=True, verbose_name='商品总价'),
        ),
    ]
