# Generated by Django 4.2 on 2023-11-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(verbose_name='基本工资')),
                ('present', models.IntegerField(verbose_name='全勤奖励')),
                ('should_issued', models.IntegerField(verbose_name='应发合计')),
                ('provide_age', models.IntegerField(verbose_name='个人养老')),
                ('treatment', models.IntegerField(verbose_name='个人医疗')),
                ('unemployed', models.IntegerField(verbose_name='个人失业')),
                ('lodging', models.IntegerField(verbose_name='住房公积金')),
                ('income_tax', models.IntegerField(verbose_name='代扣个税')),
                ('real_issued', models.IntegerField(verbose_name='实发合计')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '工资表',
            },
        ),
    ]
