# Generated by Django 4.2.7 on 2023-11-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_vacate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacate',
            name='user',
        ),
        migrations.DeleteModel(
            name='SalaryModel',
        ),
        migrations.DeleteModel(
            name='Vacate',
        ),
    ]
