# Generated by Django 4.2 on 2023-08-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=256, verbose_name='消息标识')),
                ('title', models.CharField(max_length=64, verbose_name='消息标题')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('type', models.IntegerField(verbose_name='消息类型')),
            ],
            options={
                'verbose_name_plural': '消息',
            },
        ),
    ]
