# Generated by Django 4.2 on 2023-08-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='avatar',
            field=models.CharField(max_length=256, null=True, verbose_name='消息标识'),
        ),
    ]
