# Generated by Django 4.2 on 2023-08-07 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0002_alter_notice_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='对应用户'),
        ),
    ]
