# Generated by Django 4.2.3 on 2023-07-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='姓名')),
                ('gender', models.CharField(max_length=32, null=True, verbose_name='性别')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
