# Generated by Django 4.2 on 2023-08-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='menu',
            field=models.ManyToManyField(to='user.menu', verbose_name='角色权限'),
        ),
    ]
