# Generated by Django 4.2.7 on 2023-11-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='image_drawing/')),
            ],
            options={
                'verbose_name_plural': '上传原图',
            },
        ),
        migrations.CreateModel(
            name='MaskDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='mask_drawing/')),
            ],
            options={
                'verbose_name_plural': '上传Mask',
            },
        ),
        migrations.AlterField(
            model_name='characters',
            name='menu',
            field=models.ManyToManyField(to='user.menu', verbose_name='角色权限'),
        ),
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.imagedrawing', verbose_name='原图')),
                ('mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.maskdrawing', verbose_name='mask')),
            ],
            options={
                'verbose_name_plural': '检测记录',
            },
        ),
    ]
