# Generated by Django 4.2.3 on 2023-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_managers_userinfo_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(max_length=32, null=True, verbose_name='角色'),
        ),
        migrations.AlterIndexTogether(
            name='userinfo',
            index_together={('username', 'phone')},
        ),
    ]
