# Generated by Django 4.2.3 on 2023-07-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_characters_userinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('another_name', models.CharField(max_length=64, null=True, verbose_name='菜单别名')),
                ('type', models.CharField(max_length=64, verbose_name='菜单类型')),
                ('reveal', models.BooleanField(verbose_name='是否显示')),
                ('path', models.CharField(max_length=128, null=True, verbose_name='菜单URL')),
                ('menu_name', models.CharField(max_length=128, null=True, verbose_name='菜单Name')),
                ('component_address', models.CharField(max_length=128, null=True, verbose_name='组件地址')),
                ('menu_icon', models.CharField(max_length=64, null=True, verbose_name='菜单Icon')),
                ('status', models.BooleanField(default=True, verbose_name='菜单状态')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
    ]
