# Generated by Django 4.2 on 2023-09-01 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_url', models.FileField(upload_to='banner/', verbose_name='轮播图')),
                ('type', models.IntegerField(choices=[(1, '首页轮播图'), (2, '分类详情轮播图')], verbose_name='轮播图种类')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='对应分类')),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
